name: Tag and pre-deploy consignment export
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
permissions: {}
env:
  BRANCH_NAME: version-bump-${{ github.run_id }}${{ github.run_attempt }}
jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    env:
      WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
    if: ${{ github.base_ref == 'master' && github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'Version bump') }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: sbt/setup-sbt@93e926cbdb4a428e41b4ef754124ec82925ffdc2 # v1.1.23
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - id: build
        run: |
          git config --global user.email 181243999+tna-da-bot@users.noreply.github.com
          git config --global user.name tna-da-bot
          git checkout -b $BRANCH_NAME
          git push -u origin $BRANCH_NAME
          sbt 'release with-defaults'
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
      - name: Configure AWS credentials from management account
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MANAGEMENT_ACCOUNT }}:role/TDRGithubActionsRoleMgmt
          aws-region: eu-west-2
          role-session-name: ExportPushImages
      - name: Login to ECR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ${{ secrets.MANAGEMENT_ACCOUNT }}.dkr.ecr.eu-west-2.amazonaws.com
      - name: Download Wiz CLI
        run: |
          curl -Lo wizcli https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64
          curl -Lo /tmp/wizcli-sha256 https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64-sha256
          curl -Lo /tmp/wizcli-sha256.sig https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64-sha256.sig
          chmod +x wizcli
      - name: Verify Wiz CLI signature
        run: |
          curl -Lo public_key.asc https://downloads.wiz.io/wizcli/public_key.asc
          gpg --import public_key.asc
          gpg --verify /tmp/wizcli-sha256.sig /tmp/wizcli-sha256
          echo "$(cat /tmp/wizcli-sha256) wizcli" | sha256sum --check
      - name: Run Wiz CLI directory scan
        env:
          WIZ_PROJECT: ${{ secrets.WIZ_PROJECT_TDR }}
        run: >-
          ./wizcli scan dir .
          --name tdr-consignment-export-${{ github.run_number }} --project $WIZ_PROJECT
      - name: Build image
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
          LATEST_TAG: ${{ steps.build.outputs.latest-tag }}
          MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
        run: |
          gh release create --generate-notes $LATEST_TAG bagit-export/target/universal/tdr-consignment-export.tgz export/target/universal/tdr-export.tgz
          gh pr create --fill --label 'Version bump'
          docker buildx build --output=type=docker --provenance=false --sbom=false --pull --no-cache -t $MANAGEMENT_ACCOUNT.dkr.ecr.eu-west-2.amazonaws.com/consignment-export:$LATEST_TAG .
      - name: Wiz Container Image Scan
        env:
          LATEST_TAG: ${{ steps.build.outputs.latest-tag }}
          MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
          WIZ_PROJECT: ${{ secrets.WIZ_PROJECT_TDR }}
        run: >-
          ./wizcli scan container-image $MANAGEMENT_ACCOUNT.dkr.ecr.eu-west-2.amazonaws.com/consignment-export:$LATEST_TAG
          --project $WIZ_PROJECT
      - name: Push image to ECR
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
          LATEST_TAG: ${{ steps.build.outputs.latest-tag }}
          MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
        run: |
          docker push $MANAGEMENT_ACCOUNT.dkr.ecr.eu-west-2.amazonaws.com/consignment-export:$LATEST_TAG
          gh workflow run deploy.yml -f environment=intg -f to-deploy=$LATEST_TAG
      - name: Wiz image tag
        env:
          LATEST_TAG: ${{ steps.build.outputs.latest-tag }}
          MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
        run: >-
          ./wizcli tag $MANAGEMENT_ACCOUNT.dkr.ecr.eu-west-2.amazonaws.com/consignment-export:$LATEST_TAG
      - name: Send success message
        uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@c130d20af544843b70e2a0e1a44759d4fabf3a5d # v0.0.37
        with:
          message: "*Consignment Export* :whale: Pushed version ${{ steps.build.outputs.latest-tag}} to AWS ECR"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
